version: '3'
services:
  postgres:
    image: postgres:13.5-alpine
    ports:
      - "${PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: analysis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password

volumes:
  postgres_data:
